metadata:
  name: provider
kind: Deployment
spec:
  template:
    metadata:
      name: provider
      namespace: default
      labels:
        container: provider
        project: provider
    spec:
      containers:
      - image: chungsju/provider:${project.version}
        imagePullPolicy: Always
        name: provider
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: PROVIDER_PORT
          value: '8000'
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: BW_PROFILE
          value: Docker
        ports:
        - containerPort: 8000
  replicas: 2
  selector:
    container: provider
    provider: fabric8
    project: provider
    group: com.tibco.bw
