pipeline {
    agent any
    tools { 
        // Jenkins 환경설정에서 자동으로 설치한 Maven의 Name
        maven "Maven3"
    }
	stages {
        stage('SCM Check out test') {
            steps {
               sh "ls -al"
            }
        }
        stage('Clean & Package') {
            steps {
                dir("Provider.application.parent") {
               		 sh "mvn clean package"
               	}
            }
        }
        stage('Docker Image Build') {
            steps {
            	 dir("Provider.application.parent") {
               		 sh "mvn package initialize docker:build"
               	}
            }
        }
        stage('Docker Image push') {
            steps {
                 dir("Provider.application.parent") {
               		// setting.xml 환경설정파일 참조 
                 	sh "mvn initialize docker:push -s setting.xml"
               	}
            }
        }
        stage('Kubernetes Resource') {
            steps {
                 dir("Provider.application.parent") { 
                 	sh "mvn initialize com.tibco.plugins:bw6-maven-plugin:bwfabric8json fabric8:resource"
               	} 
            }
        }
        stage('Kubernetes Resource Push to Git') {
            steps {
                 	   //sh "mvn  initialize fabric8:apply"
                 	   
                 	   //sh "git clone https://github.com/chungsju/kube_deploy.git /var/jenkins_home/workspace/kube_deploy/.git"
                 	   
                 	   sh "rm -rf /var/jenkins_home/workspace/kube_deploy/"
                 	   sh "mkdir /var/jenkins_home/workspace/kube_deploy/"
                 	   sh "git clone https://github.com/chungsju/kube_deploy.git /var/jenkins_home/workspace/kube_deploy/"
                 	   sh "cp -r Provider.application/target/classes/META-INF/fabric8/kubernetes/provider-deployment.yml /var/jenkins_home/workspace/kube_deploy/yaml/provider-yaml/"
                 	   sh "cp -r Provider.application/target/classes/META-INF/fabric8/kubernetes/provider-svc-service.yml /var/jenkins_home/workspace/kube_deploy/yaml/provider-yaml/"
                 	   
                 	   
                 	   dir("/var/jenkins_home/workspace/kube_deploy/") {
                 	   	   sh "cd  /var/jenkins_home/workspace/kube_deploy/"
		                   //sh "git pull https://github.com/chungsju/kube_deploy.git HEAD:main --allow-unrelated-histories"
	                       
	                       sh "git add -f yaml/provider-yaml"
	                       sh "git config --global user.email 'chungsju@gmail.com'"
	                       sh "git commit -m jenkins_build"
	                       withCredentials([usernamePassword(credentialsId: '3dc09248-9c5c-433f-9b4f-2416cfd9a648', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
	   
							    sh('git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/chungsju/kube_deploy.git HEAD:main')
							} 
						}
             //ghp_mpktfpXDRJN/*이건 패스워드*/ZFOuD95w35PyjNL0U3x1QHEGF    
            }
        }
    }
}
